//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIOperandConfig) DeepCopyInto(out *APIOperandConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIOperandConfig.
func (in *APIOperandConfig) DeepCopy() *APIOperandConfig {
	if in == nil {
		return nil
	}
	out := new(APIOperandConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConfig) DeepCopyInto(out *AgentConfig) {
	*out = *in
	out.Submodule = in.Submodule
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConfig.
func (in *AgentConfig) DeepCopy() *AgentConfig {
	if in == nil {
		return nil
	}
	out := new(AgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.AvailableCapabilities != nil {
		in, out := &in.AvailableCapabilities, &out.AvailableCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSubmoduleConfig) DeepCopyInto(out *AgentSubmoduleConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSubmoduleConfig.
func (in *AgentSubmoduleConfig) DeepCopy() *AgentSubmoduleConfig {
	if in == nil {
		return nil
	}
	out := new(AgentSubmoduleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositoryConfig) DeepCopyInto(out *GitRepositoryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositoryConfig.
func (in *GitRepositoryConfig) DeepCopy() *GitRepositoryConfig {
	if in == nil {
		return nil
	}
	out := new(GitRepositoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraCDC) DeepCopyInto(out *JiraCDC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraCDC.
func (in *JiraCDC) DeepCopy() *JiraCDC {
	if in == nil {
		return nil
	}
	out := new(JiraCDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JiraCDC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraCDCList) DeepCopyInto(out *JiraCDCList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JiraCDC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraCDCList.
func (in *JiraCDCList) DeepCopy() *JiraCDCList {
	if in == nil {
		return nil
	}
	out := new(JiraCDCList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JiraCDCList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraCDCSpec) DeepCopyInto(out *JiraCDCSpec) {
	*out = *in
	in.JiraInstance.DeepCopyInto(&out.JiraInstance)
	in.SyncTarget.DeepCopyInto(&out.SyncTarget)
	out.GitRepository = in.GitRepository
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = new(OperandConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncConfig != nil {
		in, out := &in.SyncConfig, &out.SyncConfig
		*out = new(SyncConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentConfig != nil {
		in, out := &in.AgentConfig, &out.AgentConfig
		*out = new(AgentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraCDCSpec.
func (in *JiraCDCSpec) DeepCopy() *JiraCDCSpec {
	if in == nil {
		return nil
	}
	out := new(JiraCDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraCDCStatus) DeepCopyInto(out *JiraCDCStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	out.OperandStatus = in.OperandStatus
	out.ComponentStatus = in.ComponentStatus
	in.AgentStatus.DeepCopyInto(&out.AgentStatus)
	if in.CurrentTask != nil {
		in, out := &in.CurrentTask, &out.CurrentTask
		*out = new(TaskInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraCDCStatus.
func (in *JiraCDCStatus) DeepCopy() *JiraCDCStatus {
	if in == nil {
		return nil
	}
	out := new(JiraCDCStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraInstanceConfig) DeepCopyInto(out *JiraInstanceConfig) {
	*out = *in
	if in.ProxyConfig != nil {
		in, out := &in.ProxyConfig, &out.ProxyConfig
		*out = new(ProxyConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraInstanceConfig.
func (in *JiraInstanceConfig) DeepCopy() *JiraInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(JiraInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandConfig) DeepCopyInto(out *OperandConfig) {
	*out = *in
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(APIOperandConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UIOperandConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandConfig.
func (in *OperandConfig) DeepCopy() *OperandConfig {
	if in == nil {
		return nil
	}
	out := new(OperandConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandStatus) DeepCopyInto(out *OperandStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandStatus.
func (in *OperandStatus) DeepCopy() *OperandStatus {
	if in == nil {
		return nil
	}
	out := new(OperandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandsStatus) DeepCopyInto(out *OperandsStatus) {
	*out = *in
	out.API = in.API
	out.UI = in.UI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandsStatus.
func (in *OperandsStatus) DeepCopy() *OperandsStatus {
	if in == nil {
		return nil
	}
	out := new(OperandsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncConfig) DeepCopyInto(out *SyncConfig) {
	*out = *in
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(bool)
		**out = **in
	}
	if in.ActiveIssuesOnly != nil {
		in, out := &in.ActiveIssuesOnly, &out.ActiveIssuesOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncConfig.
func (in *SyncConfig) DeepCopy() *SyncConfig {
	if in == nil {
		return nil
	}
	out := new(SyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncTargetConfig) DeepCopyInto(out *SyncTargetConfig) {
	*out = *in
	if in.IssueKeys != nil {
		in, out := &in.IssueKeys, &out.IssueKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncTargetConfig.
func (in *SyncTargetConfig) DeepCopy() *SyncTargetConfig {
	if in == nil {
		return nil
	}
	out := new(SyncTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskInfo) DeepCopyInto(out *TaskInfo) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(TaskProgress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskInfo.
func (in *TaskInfo) DeepCopy() *TaskInfo {
	if in == nil {
		return nil
	}
	out := new(TaskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskProgress) DeepCopyInto(out *TaskProgress) {
	*out = *in
	if in.EstimatedTimeRemaining != nil {
		in, out := &in.EstimatedTimeRemaining, &out.EstimatedTimeRemaining
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskProgress.
func (in *TaskProgress) DeepCopy() *TaskProgress {
	if in == nil {
		return nil
	}
	out := new(TaskProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIOperandConfig) DeepCopyInto(out *UIOperandConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIOperandConfig.
func (in *UIOperandConfig) DeepCopy() *UIOperandConfig {
	if in == nil {
		return nil
	}
	out := new(UIOperandConfig)
	in.DeepCopyInto(out)
	return out
}
